import { useCallback, useEffect, useState } from 'react';
import { Button, Card, Form, Modal, Tab, Tabs } from 'react-bootstrap';
import { Link } from 'react-router-dom';
import { profilesApi } from '../api/endpoints';
import type { AttributeValueInput, ProfileEditor, Project } from '../api/types';
import { AttributeValueEditor } from '../components/AttributeValueEditor';
import { DataTable } from '../components/DataTable'; import type { Column } from '../components/DataTable';
export function ProfilePage(){
 const [profile,setProfile]=useState<ProfileEditor|null>(null);const [error,setError]=useState('');const [selected,setSelected]=useState<string[]>([]);const [show,setShow]=useState(false);const [name,setName]=useState('');const [start,setStart]=useState('');const [description,setDescription]=useState('');const [tags,setTags]=useState('');
 const load=useCallback(()=>profilesApi.me().then(setProfile).catch((e:Error)=>setError(e.message)),[]);useEffect(()=>{void load();},[load]);
 const save=async(attributeDefinitionId:string,value:AttributeValueInput)=>{if(!profile)return;try{await profilesApi.autosave(profile.id,profile.version,[{attributeDefinitionId,value}]);await load();}catch(e){setError((e as Error).message);}};
 if(!profile)return <Card><Card.Body>{error||'Loading…'}</Card.Body></Card>;
 const value=(id:string)=>profile.values.find((x)=>x.attributeDefinitionId===id)?.value;
 const columns:Column<Project>[]=[{key:'name',header:'Name',render:(x)=>x.name},{key:'period',header:'Period',render:(x)=>`${new Date(x.periodStart).toLocaleDateString()} – ${x.periodEnd?new Date(x.periodEnd).toLocaleDateString():'now'}`},{key:'tags',header:'Tags',render:(x)=>x.tags.join(', ')}];
 return <Card><Card.Body><Card.Title>{profile.displayName||'Candidate profile'}</Card.Title>{error&&<p className="text-danger">{error}</p>}<Tabs defaultActiveKey="me" className="mb-3"><Tab eventKey="me" title="Me"><div className="d-grid gap-3">{profile.builtInDefinitions.map((d)=><div key={d.id}><Form.Label>{d.name}</Form.Label><AttributeValueEditor dataType={d.dataType} options={d.options} value={value(d.id)??{stringValue:null,numericValue:null,dateValue:null,periodStart:null,periodEnd:null,boolValue:null,selectedOptionId:null,imageUrl:null}} onChange={(v)=>void save(d.id,v)}/></div>)}</div></Tab><Tab eventKey="info" title="Info"><div className="d-grid gap-3">{profile.infoDefinitions.map((d)=><div key={d.id}><Form.Label>{d.name}</Form.Label><AttributeValueEditor dataType={d.dataType} options={d.options} value={value(d.id)!} onChange={(v)=>void save(d.id,v)}/></div>)}</div></Tab><Tab eventKey="projects" title="Projects"><DataTable columns={columns} rows={profile.projects} rowKey={(x)=>x.id} selectedIds={selected} onSelectionChange={setSelected} emptyText="No projects." toolbar={<div className="d-flex gap-2"><Button size="sm" onClick={()=>setShow(true)}>Add project</Button><Button size="sm" variant="outline-danger" disabled={!selected.length} onClick={async()=>{await profilesApi.removeProjects(profile.id,selected);setSelected([]);await load();}}>Delete</Button></div>}/></Tab><Tab eventKey="cvs" title="CVs"><table className="table"><tbody>{profile.cvs.map((x)=><tr key={x.id}><td><Link to={`/cvs/${x.id}`}>{x.positionTitle}</Link></td><td>{x.status}</td></tr>)}</tbody></table></Tab></Tabs></Card.Body><Modal show={show} onHide={()=>setShow(false)} centered><Modal.Header closeButton><Modal.Title>Add project</Modal.Title></Modal.Header><Modal.Body className="d-grid gap-2"><Form.Control placeholder="Name" value={name} onChange={(e)=>setName(e.target.value)}/><Form.Control type="date" value={start} onChange={(e)=>setStart(e.target.value)}/><Form.Control as="textarea" placeholder="Markdown description" value={description} onChange={(e)=>setDescription(e.target.value)}/><Form.Control placeholder="Tags, comma separated" value={tags} onChange={(e)=>setTags(e.target.value)}/></Modal.Body><Modal.Footer><Button disabled={!name||!start} onClick={async()=>{await profilesApi.addProject(profile.id,{name,periodStart:new Date(start).toISOString(),periodEnd:null,description,tags:tags.split(',').map(x=>x.trim()).filter(Boolean)});setShow(false);await load();}}>Save</Button></Modal.Footer></Modal></Card>;
}
